# Generated by Django 5.1 on 2024-09-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_productbrand_alter_product_slug_alter_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='images/products', verbose_name='تصویر محصول'),
        ),
    ]
