# Generated by Django 5.1 on 2024-09-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
