# Generated by Django 5.1.1 on 2024-09-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_footerlingbox_alter_sitesetting_site_logo_footerlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterLingBox',
            new_name='FooterLinkBox',
        ),
    ]
