# Generated by Django 5.1.1 on 2024-09-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_slider_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='images/slider/django.jpg', verbose_name='تصویر اسلایدر'),
        ),
    ]
