# Generated by Django 5.1.1 on 2024-09-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='images/slider', verbose_name='تصویر اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(verbose_name='لینک'),
        ),
    ]
