# Generated by Django 5.1.1 on 2024-09-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='titel',
            new_name='title',
        ),
    ]
