# Generated by Django 5.1.1 on 2024-10-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0011_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله  ', 'verbose_name_plural': 'نظرات مقاله'},
        ),
    ]
